title: Ilona Kalinina
description: Software Development Engineer
url: "https://Ilona-a-k.github.io" 
baseurl: ""
github_username: Ilona-a-k

# Build settings
markdown: kramdown
#theme: minima

author:
  name             : "Ilona Kalinina"
  avatar           : "/assets/images/bio-photo.jpg"
  location         : "Belgrade"

# Minimal Mistakes settings
minimal_mistakes_skin: "air" # "default", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
main_lang: en
logo: /assets/images/logo.png

# Navigation
navigation:
  - text: "Home"
    url: "/"
  - text: "About"
    url: "/#about"
  - text: "Experience"
    url: "/#experience"
  - text: "Projects"
    url: "/#projects"
  - text: "Education"
    url: "/#education"
  - text: "Contact"
    url: "/#contact"

# Social links
social_links:
  - type: github
    link: "https://github.com/Ilona-a-k"
  - type: linkedin
    link: "https://www.linkedin.com/in/ilonakalinina"
  - type: email
    link: "mailto:ilona.a.kalinina@gmail.com"
