title: Ilona Kalinina
description: Software Development Engineer
url: "https://Ilona-a-k.github.io" # Replace with your GitHub Pages URL
baseurl: ""
github_username: Ilona-a-k

# Build settings
markdown: kramdown
theme: minima

# Minimal Mistakes settings
main_lang: en
logo: /assets/images/logo.png

# Navigation
navigation:
  - text: "Home"
    url: "/"
  - text: "About"
    url: "/#about"
  - text: "Experience"
    url: "/#experience"
  - text: "Projects"
    url: "/#projects"
  - text: "Education"
    url: "/#education"
  - text: "Contact"
    url: "/#contact"

# Social links
social_links:
  - type: github
    link: "https://github.com/Ilona-a-k"
  - type: linkedin
    link: "https://www.linkedin.com/in/ilonakalinina"
  - type: email
    link: "mailto:ilona.a.kalinina@gmail.com"
